### ISSUE TITLE
syntax-color-comment and syntax-color-string

### ISSUE THREAD

**Issue by scls19fr** [atom/base16-tomorrow-light-theme#4]
Hello,

I forked https://github.com/atom/base16-tomorrow-light-theme/ to create a syntax theme quite close to BBEdit one's https://github.com/scls19fr/aa-light-theme. 

I'm new to Atom syntax theme creation and I had some difficulties to change
- comments colors
- string colors

Maybe you might add in `syntax-variables.less`
- `syntax-color-comment`
- `syntax-color-string`

and use these 2 variables in `index.less`

```
.comment {
  color: @syntax-color-comment;
}

.string {
  color: @syntax-color-string;

  &.regexp {
    color: @cyan;
  }

  &.other.link {
    color: @red;
  }
}
```

Kind regards

**Comment by simurai** [comment]
The [language entity colors](https://github.com/atom/base16-tomorrow-light-theme/blob/master/styles/syntax-variables.less#L34-L46) were initially added to highlight code in autocomplete and not necessarly for syntax highlighting. In this theme they are currently not used in `index.less`. That might be a bit confusing. Should that be documented more clearly?

When styling a theme, I find it easier if all the variables tell how they will look. Like in the example above:

```less
.string {
  color: @syntax-color-string;
  &.regexp {
    color: @cyan;
  }
```

you can't tell what color `@syntax-color-string` is and have to check where that variable is defined.

On the other hand, if a color name is used:

```less
.string {
  color: @green;
  &.regexp {
    color: @cyan;
  }
```

it's easier to imagine and test if the syntax looks correct.

That said, you're certainly free to name and structure your own theme however you prefer. The only rule is that all syntax themes should add a `syntax-variables.less` file that includes (but is not limited to) these variables: https://github.com/atom/atom/blob/master/static/variables/syntax-variables.less so other packages can use them and know that the variables exist.
